version: '3.9'

services:
  api:
    build: .
    container_name: api
    ports:
      - '3000:3000'
    networks:
      - sw-graphql
    environment:
      - DATABASE_URL=postgresql://postgres:passw123@database:5432/starwars-db
      - SWAPI_BASE_URL=https://swapi.dev/api
  database:
    image: postgres:13.1-alpine
    container_name: database
    networks:
      - sw-graphql
    environment:
      - POSTGRES_PASSWORD=passw123
networks:
  sw-graphql:
    name: sw-graphql-network
    driver: bridge
